INO=curing/curing.ino

upload:
	arduino --board arduino:avr:mega --verbose-upload --upload $(INO)

verify:
	arduino --board arduino:avr:mega --verbose-build --preserve-temp-files --verify $(INO)


clean:
