INO=curing/curing.ino

verify:
	arduino --board arduino:avr:mega --verbose-build --preserve-temp-files --verify $(INO)

upload:
	arduino --board arduino:avr:mega --verbose-upload --upload $(INO)

clean:
